# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.7 on 2018-03-16 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 1.11.7 on 2018-02-27 05:59
from __future__ import unicode_literals

from django.db import migrations, models
>>>>>>> master


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='item_template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='商品名字')),
                ('define_code', models.CharField(max_length=64, verbose_name='自定义编码')),
                ('brand_id', models.SmallIntegerField(verbose_name='品牌ID')),
                ('barcode', models.CharField(max_length=64, verbose_name='标准条形码 必须唯一')),
                ('cost_price', models.IntegerField(verbose_name='建立成本价')),
                ('default_price', models.IntegerField(verbose_name='默认价格(建立零售价)')),
                ('image_url', models.CharField(max_length=256, verbose_name='默认图片地址')),
                ('banner_url', models.CharField(max_length=256, verbose_name='banner图地址')),
                ('introduction_page', models.CharField(max_length=256, verbose_name='介绍页面 不存在时可为null')),
                ('status', models.SmallIntegerField(default=0, verbose_name='状态 0-可用 1-提交审核 2-审核不通过 3-失效')),
                ('description', models.CharField(max_length=512, verbose_name='商品描述')),
                ('uploaders_passport_id', models.BigIntegerField(default=0, verbose_name='上传者通行证ID')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('ascription_type', models.IntegerField(default=0, verbose_name='操作类型：1，POS,0供应链')),
            ],
            options={
                'db_table': 'item_template',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
=======
>>>>>>> master
            name='item_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pid', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('sort', models.IntegerField(default=0)),
                ('top', models.IntegerField(default=0)),
                ('icon', models.CharField(max_length=256)),
                ('image', models.CharField(max_length=256)),
                ('ascription_type', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
<<<<<<< HEAD
                'db_table': 'item_type',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='item_unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='单位标题')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态 0-不启动 1启动')),
            ],
            options={
                'db_table': 'item_unit',
            },
        ),
        migrations.AddField(
            model_name='item_template',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.item_type'),
        ),
        migrations.AddField(
            model_name='item_template',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.item_unit'),
        ),
=======
                'ordering': ['-id'],
            },
        ),
>>>>>>> master
    ]
