# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 03:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='head_url',
            field=models.FileField(default=datetime.datetime(2017, 12, 22, 3, 30, 3, 379876, tzinfo=utc), upload_to='./upload', verbose_name='头像'),
            preserve_default=False,
        ),
    ]
