# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='menu',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menu',
            name='sort',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menu',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
